// Objective-C API for talking to github.com/fatedier/frp/cmd/frpc Go package.
//   gobind -lang=objc github.com/fatedier/frp/cmd/frpc
//
// File is generated by gobind. Do not edit.

#ifndef __FrpManager_H__
#define __FrpManager_H__

@import Foundation;
#include "Universe.objc.h"


FOUNDATION_EXPORT void FrpManagerRunFrpc(void);

#endif
