
// Objective-C API for talking to the following Go packages
//
//	github.com/fatedier/frp/cmd/frpc
//
// File is generated by gomobile bind. Do not edit.
#ifndef __FrpManager_FRAMEWORK_H__
#define __FrpManager_FRAMEWORK_H__

#include "FrpManager.objc.h"
#include "universe.objc.h"

#endif
